version: '3'
services:

# Laravel Application
  laravel:
    build: .
    ports:
      - "80:80"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  # Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
        - dbdata:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel

  # nginx server
  nginx:
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
      - logs:/var/logs/nginx/access.log
      - logs:/var/logs/nginx/error.log
    networks:
      - laravel

# Network
networks:
  laravel:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  logs:
    driver: local