version: '3'
services:
# Laravel Application
  laravel:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
# Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql/

#Volumes
volumes:
  dbdata:
    driver: local